# Generated by Django 5.1 on 2024-10-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_status', 'Can change status')]},
        ),
    ]
