# Generated by Django 5.1 on 2024-10-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_content', 'Can edit content')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
