# Generated by Django 5.1 on 2024-10-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_article', 'Can publish article')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
