# Generated by Django 5.1 on 2024-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='newsletterhistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodic',
            field=models.CharField(choices=[('OT', 'onetime'), ('PD', 'daily'), ('PW', 'weekly'), ('PM', 'monthly')], default='OT', max_length=2, verbose_name='Переодичность'),
        ),
    ]
