# Generated by Django 5.1 on 2024-08-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletters', to='newsapp.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodic',
            field=models.CharField(choices=[('OT', 'onetime'), ('PD', 'daily'), ('PW', 'weekly'), ('PM', 'monthly')], default='OT', max_length=2, verbose_name='Периодичность'),
        ),
    ]
