# Generated by Django 5.1 on 2024-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_newsletter_message_alter_newsletter_periodic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(related_name='newsletters', to='newsapp.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodic',
            field=models.CharField(choices=[('OT', 'разовая'), ('PD', 'ежедневная'), ('PW', 'еженедельная'), ('PM', 'ежемесячная')], default='OT', max_length=2, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('ON', 'включена'), ('OFF', 'выключена')], default='OFF', max_length=3, verbose_name='Статус'),
        ),
    ]
